### ISSUE TITLE
Update materialized view on save

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/api.tnris.org#1]
<a href="https://github.com/JasonKleinert"><img src="https://avatars2.githubusercontent.com/u/5649664?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [JasonKleinert](https://github.com/JasonKleinert)**
_Tuesday Apr 09, 2019 at 13:17 GMT_
_Originally opened as https://github.com/TNRIS/data.tnris.org/issues/182_

----

use Django signals and django.db.connection to update the materialized view wheen a model is saved. I think we can use Django siganls in place of db triggers to update our views on save. connection can be used to run thee raw sql necessary to update the view. Not sure what performance will be like, but worth trying out.
1. https://stackoverflow.com/questions/1197674/actions-triggered-by-field-change-in-django
1. https://stackoverflow.com/questions/5931586/raw-sql-queries-in-django-views

**Comment by adambreznicky** [comment]
after testing, simple implementation of signals run the function synchronously so every save requires waiting for the view refresh query to finish (several loooong seconds). 
to do this more properly and maintain normal performance, the query/signal should be executed async or as a background task. reading through research is suggesting celery tasks. 
i'll continue testing and implementing alternative options.
onward...

**Comment by JasonKleinert** [comment]
Adding a task queue could be a nice addition to allow for more advanced functionality.

**Comment by adambreznicky** [comment]
better yet! the signal could just fire a lambda that does the 'task'. this  helps modulate the task itself and reduces code/maintenance within the much larger api application as a whole

**Comment by JasonKleinert** [comment]
That would make it a lot less complex to maintain/understand and faster to implement. Like it!

**Comment by adambreznicky** [comment]
resolved via commit 4d360aa94a758ebe02fbfa5d0624705c204c3ce3
all admin console changes fire lambda to refresh their associated materialized views with the exception of the 'areas' view.
routine lambda refresh of views will continue to run as a safeguard/backup mechanism as well as to handle 'areas' view since it doesn't fire on save
