### ISSUE TITLE
migrate contact app

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/api.tnris.org#23]
the contact app is currently a separate api. embracing a comprehensive and long-term vision for our stack, it should probably be migrated into api.tnris.org as part of a consolidation effort. this would also open up the ability to manage the various google sheets, email templates, ticketing emails, etc. via the django admin console opposed to updating the js code for these types of updates. all apps using the current contact app would then need to be redeployed as pointing toward the new api.tnris.org endpoints. when completed, the contact app repo can go away.

**Comment by JasonKleinert** [comment]
Sounds like a good plan to me.

**Comment by adambreznicky** [comment]
resolved a3e1ccbb390a22d6fb4e0b254799fcf0215c32e3
