### ISSUE TITLE
Copy Link URL for DataHub Images

### ISSUE THREAD

**Issue by christoball** [TNRIS/api.tnris.org#24]
Can we add a copy link url button on DataHub Images?

This would be useful for incorporating them into articles or other places on the site.

@adambreznicky "i know i had added a copy link url button for the tnris.org images and docs tables in the admin console. are you imaging something similar for this?"

Yes, that's what I'm thinking. I figure it would make the most sense somewhere under a data collection editing, under the images. Possibly to the right of where the url shows up or below it.

![image](https://user-images.githubusercontent.com/1877550/64353439-60232880-cfc3-11e9-9c0e-c1de20931840.png)

**Comment by adambreznicky** [comment]
resolved 43a1941c8dcae8ee42132b4a8bbceea3c34143fa
