### ISSUE TITLE
Cancelled Training

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/api.tnris.org#25]
I think we need a third option for the training classes Open, Closed, Cancelled.

**Comment by adambreznicky** [comment]
as per our discussion, i think we should have an in person meeting about this change with admin personnel before we make any hasty decisions. making this change is semi-significant insofar as database schema updates, api enhancements, and frontend adjustments. and ultimately, doesn't really solve the source of the problem or capture all the possible scenarios which may need handling. i'll close for now and we can create a new issue with more direct instruction for the changes which result from the personnel meeting.
