### ISSUE TITLE
resize map collection thumbs

### ISSUE THREAD

**Issue by christoball** [TNRIS/api.tnris.org#28]

**Comment by adambreznicky** [comment]
most thumbnails uploaded seem to be ~10mb. they'll need to be downloaded, resized, deleted in the map collection form (using the checkbox and save button), then re-uploaded

**Comment by adambreznicky** [comment]
hey @christoball !
yesterday you were "RWPD map collection to a more web optimized version" in issue 67, which i assume was resizing/formatting as necessary. seems related to this issue. were you optimizing/resizing all the thumbnails or only the RWPD one?
looking at this old issue, they should all be refreshed just like ya did on RWPD yesterday.

**Comment by christoball** [comment]
@adambreznicky yes, this is all done, thanks for looping back around on this.
