### ISSUE TITLE
Date Published Field

### ISSUE THREAD

**Issue by christoball** [TNRIS/api.tnris.org#31]
Adding the ability to have a date published field so the latest data on tnris front page shows the most recently added dataset

attn: @adambreznicky

**Comment by christoball** [comment]
@adambreznicky i realized this is datahub, creating the issue there.

**Comment by adambreznicky** [comment]
this does require model and api endpoint updates so this is a proper place for this issue. it'll require frontend updates also so it's not a problem to exist over in that repo simultaneously

**Comment by adambreznicky** [comment]
resolved fde9c53d012c25af4c53f1d00996f262bfc158c3
