### ISSUE TITLE
Console Weirdness

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/api.tnris.org#32]
Asset file show in console but no data in s3.

<img width="1193" alt="Screen Shot 2019-09-26 at 8 03 57 AM" src="https://user-images.githubusercontent.com/8459928/65690829-773ebe80-e035-11e9-8bc5-b85e16ac62be.png">
<img width="848" alt="Screen Shot 2019-09-26 at 8 04 23 AM" src="https://user-images.githubusercontent.com/8459928/65690851-7e65cc80-e035-11e9-839b-d5d83046df0e.png">
<img width="1803" alt="Screen Shot 2019-09-26 at 8 09 50 AM" src="https://user-images.githubusercontent.com/8459928/65690854-7efe6300-e035-11e9-8f8b-302c355f2c97.png">

**Comment by adambreznicky** [comment]
looks like a remnant of the original etl to me. i had found one in the past as well. i suggest ya check the box to delete the file in the admin console and save. then re-upload through the admin console. if that goes as it should, let's close this ticket and file it as an anomaly. if you have an issue or find any more of these, holler.
