### ISSUE TITLE
Dataset collection increase padding-bottom for black footer bar

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/api.tnris.org#37]
if a user expands the forms in a dataset collection in the api admin console and scrolls to the bottom, the black footer bar at the bottom covers up some of the form. i think this can be solved with a simple padding-bottom addition or increase. 

this issue may exist for forms in other apps/tables in the api admin console.

**Comment by adambreznicky** [comment]
resolved 37ab1884480249bc7cc3b114de4cd2fc7f360388
