### ISSUE TITLE
Add UUID field in LORE

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/api.tnris.org#5]
Can we please add a field for UUID similar to the Collection ID field in Lt. Commander Data. 
We would like to be able to search for Historical collections using the UUID. 
![image](https://user-images.githubusercontent.com/23489372/59514918-884b3180-8e83-11e9-9d49-850b716c270c.png)

**Comment by adambreznicky** [comment]
closed via commit 16f267ca6f685012b53f2c8f37b3e25f25f21e69
