### ISSUE TITLE
Add check box for "Fully Scanned" collections 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/api.tnris.org#50]
Can we please add a check box in the 'Collection Information' Section labelled 'Fully Scanned' 
Is it possible to list it in line with the number for boxes or just below? 
![image](https://user-images.githubusercontent.com/23489372/70644361-7bc44d80-1c08-11ea-9367-44ea510df667.png)

**Comment by adambreznicky** [comment]
resolved ede7246d516feeed3108d296b0785aeb096f7047
