### ISSUE TITLE
Add check box for "Photo Index Only" collections 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/api.tnris.org#51]
Please add check box with label 'Photo Index Only' in "Collection Information" section of record. Please add between Number of Boxes Text Box and Public checkbox
Thank you!

**Comment by jwhaney** [comment]
@csidenblad I'm assuming the default is False/Unchecked?

**Comment by jwhaney** [comment]
nm, @LaurenKirk answered my question.
