### ISSUE TITLE
Add drop down option for "Erasing"

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/api.tnris.org#52]
We would like to record, and filter for,  collections/products that need erasing. Can you add a field with a drop down listing the following options: 

- Clean 
- Needs Erasing 
- -----

Default should be ------ (blank) 
Please place field within the "Products" section between 'Print Type' and 'Physical Location'
![image](https://user-images.githubusercontent.com/23489372/70644892-816e6300-1c09-11ea-87d4-35678675b6e0.png)

**Comment by csidenblad** [comment]
change to boolean (check box)

- Clean = TRUE
- Needs Erasing = FALSE

default is 'Clean'

Clean refers to collections that have been reviewed and are ready to been scanned, no erasing of frames needed.

**Comment by jwhaney** [comment]
Danke!

**Comment by jwhaney** [comment]
just to update this issue for documentation, after talking with @csidenblad & @LaurenKirk , the default will now be false or unchecked/dirty/not clean. updates to the values for this new clean_status field have been made in the db based on remarks that included the substring 'erase' or similar. this leaves some room for error and those collections should probably be double checked.

so to give a summary as of now, there are 122 products that are now clean_status = false. i believe there are 94 unique collections/collection ids that have a product clean status = false. everything else is checked or true/clean.

i'm working on getting the filter set up now. hopefully get that done and the app redeployed before my holiday starts.......

**Comment by jwhaney** [comment]
resolved via PR #58
