### ISSUE TITLE
Add Field for GIO Community Meeting Agenda to API

### ISSUE THREAD

**Issue by christoball** [TNRIS/api.tnris.org#55]
@adambreznicky Add field to include url link to latest GIS Community meeting agenda for displaying download agenda link, as seen below

<img width="311" alt="Screen Shot 2019-12-16 at 1 51 48 PM" src="https://user-images.githubusercontent.com/1877550/70938149-3d190380-200b-11ea-8a03-ecd265878b57.png">

Below is the current code added to gio_calendar_quad.js and gio_calendar_next_cm.js . Would need to edit Javascript so its not hardcoded once the API is ready.

`<a class="btn btn-tnris btn-md" href="https://tnris-org-static.s3.amazonaws.com/documents/GISComm_Agenda_20200114.pdf">Download Agenda</a>`

**Comment by jwhaney** [comment]
closed via PR #56
