### ISSUE TITLE
Add "Fully Scanned" filter 

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/api.tnris.org#61]
Please add a filter for "Fully Scanned" collections based on Fully Scanned Field being True. 
Consultants would like to be able to quickly identify which collections have been fully scanned and are available for bulk order.

**Comment by LaurenKirk** [comment]
@jwhaney @csidenblad Hey John, can you please give us an update on when the "Fully Scanned" filter option will go live?  Ideally, we'd like to have it up on or before March 2nd.

Thank you!!
