### ISSUE TITLE
ovewrite file on Map Downloads upload

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/api.tnris.org#63]
@e00o MSD app table 'Map Downloads' permits his uploading of map PDFs for downloading on the /maps page of tnris.org.
if updating a record in the admin console, it's possible to choose a new file to upload and overwrite the currently existing one. currently, doing this deletes the old PDF from s3 but doesn't update the download url within the database to the newly uploaded one.

solution should be either to disable the ability to 'choose file' and overwrite that field for a record --or-- to fix the problem so an overwrite upload updates the link field in the database.

**Comment by jwhaney** [comment]
closed via pr #66
