### ISSUE TITLE
tnris_org documents auto download

### ISSUE THREAD

**Issue by adambreznicky** [TNRIS/api.tnris.org#64]
opening the Documents table in the admin console for the tnris_org app automatically downloads a random MP3 on page load
weeeeiiiiiirrrrdddddddddddddd

**Comment by adambreznicky** [comment]
related to the TINY PREVIEW column on the list view

**Comment by jwhaney** [comment]
deleted the .mp3 which solved the issue this time. probably need to write in some preventative function to prevent .mp3s from being uploaded to the documents directory. i'll look into it.

**Comment by jwhaney** [comment]
after discussion, decided to remove tiny preview from the tnris_org /documents upload as i do not see it being as valuable as the tnris_org /images upload. the auto-download wasn't the only problem, there were other console errors dealing with the url structure of the tnris-org-static s3 bucket for some reason.

kept it simple and just remove the preview for /documents and keep it for /images.

**Comment by jwhaney** [comment]
closed via pr #65
