### ISSUE TITLE
update django to latest 3.0 version

### ISSUE THREAD

**Issue by jwhaney** [TNRIS/api.tnris.org#71]
Remediation
Upgrade Django to version 2.2.9 or later. For example:
Django>=2.2.9

Vulnerable versions: >= 2.0.0, < 2.2.9
Patched version: 2.2.9
Django before 1.11.27, 2.x before 2.2.9, and 3.x before 3.0.1 allows account takeover. A suitably crafted email address (that is equal to an existing user's email address after case transformation of Unicode characters) would allow an attacker to be sent a password reset token for the matched user account. (One mitigation in the new releases is to send password reset tokens only to the registered user email address.)

**Comment by jwhaney** [comment]
closed via #72 
will continue to test the develop branch now that its merged but i think it should be good.

**Comment by jwhaney** [comment]
re-opening due to difficulties with updating to latest django version. picture widgets i think are resolved but there are a few other issues that need to be further investigated.

**Comment by adambreznicky** [comment]
resolved via commit a4582f4e9b7dc6c1626a037f281c220d87fb164f
